manifest:
  remotes:
    - name: eurus-project
      url-base: https://github.com/eurus-project
  projects:
    - name: zephyr
      remote: eurus-project
      revision: boards/weact_stm32h562_core
      import: true
  self:
    path: efc
