manifest:
  remotes:
    - name: eurus-project
      url-base: https://github.com/eurus-project
    - name: upstream-zephyr
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: upstream-zephyr
      revision: main
      import: true
  self:
    path: efc
